[2023-06-13T13:12:15.652+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: applicants.transform manual__2023-06-13T13:12:10.083421+00:00 [queued]>
[2023-06-13T13:12:15.659+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: applicants.transform manual__2023-06-13T13:12:10.083421+00:00 [queued]>
[2023-06-13T13:12:15.660+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-13T13:12:15.739+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): transform> on 2023-06-13 13:12:10.083421+00:00
[2023-06-13T13:12:15.746+0000] {standard_task_runner.py:57} INFO - Started process 2340 to run task
[2023-06-13T13:12:15.751+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'applicants', 'transform', 'manual__2023-06-13T13:12:10.083421+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpuxktoqmo']
[2023-06-13T13:12:15.752+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask transform
[2023-06-13T13:12:15.826+0000] {task_command.py:410} INFO - Running <TaskInstance: applicants.transform manual__2023-06-13T13:12:10.083421+00:00 [running]> on host 9e894d1b1662
[2023-06-13T13:12:15.947+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='applicants' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-06-13T13:12:10.083421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-13T13:12:10.083421+00:00'
[2023-06-13T13:12:15.949+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: transform() missing 1 required positional argument: 'df'
[2023-06-13T13:12:15.957+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=applicants, task_id=transform, execution_date=20230613T131210, start_date=20230613T131215, end_date=20230613T131215
[2023-06-13T13:12:15.981+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 102 for task transform (transform() missing 1 required positional argument: 'df'; 2340)
[2023-06-13T13:12:16.003+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-13T13:12:16.024+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
