[2023-06-09T09:09:55.470+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: applicants.load manual__2023-06-09T09:09:49.785814+00:00 [queued]>
[2023-06-09T09:09:55.479+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: applicants.load manual__2023-06-09T09:09:49.785814+00:00 [queued]>
[2023-06-09T09:09:55.480+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-09T09:09:55.497+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load> on 2023-06-09 09:09:49.785814+00:00
[2023-06-09T09:09:55.505+0000] {standard_task_runner.py:57} INFO - Started process 2094 to run task
[2023-06-09T09:09:55.509+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'applicants', 'load', 'manual__2023-06-09T09:09:49.785814+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpgouj7rba']
[2023-06-09T09:09:55.510+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask load
[2023-06-09T09:09:55.560+0000] {task_command.py:410} INFO - Running <TaskInstance: applicants.load manual__2023-06-09T09:09:49.785814+00:00 [running]> on host 9e894d1b1662
[2023-06-09T09:09:55.642+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='applicants' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-06-09T09:09:49.785814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-09T09:09:49.785814+00:00'
[2023-06-09T09:09:55.644+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load() missing 1 required positional argument: 'df5'
[2023-06-09T09:09:55.652+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=applicants, task_id=load, execution_date=20230609T090949, start_date=20230609T090955, end_date=20230609T090955
[2023-06-09T09:09:55.667+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task load (load() missing 1 required positional argument: 'df5'; 2094)
[2023-06-09T09:09:55.680+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-09T09:09:55.697+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
