[2023-06-10T15:56:51.897+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: applicants.load manual__2023-06-10T15:56:39.147730+00:00 [queued]>
[2023-06-10T15:56:51.910+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: applicants.load manual__2023-06-10T15:56:39.147730+00:00 [queued]>
[2023-06-10T15:56:51.911+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-10T15:56:51.934+0000] {taskinstance.py:1327} INFO - Executing <Task(MsSqlOperator): load> on 2023-06-10 15:56:39.147730+00:00
[2023-06-10T15:56:51.942+0000] {standard_task_runner.py:57} INFO - Started process 14418 to run task
[2023-06-10T15:56:51.946+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'applicants', 'load', 'manual__2023-06-10T15:56:39.147730+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpsrosd75j']
[2023-06-10T15:56:51.946+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask load
[2023-06-10T15:56:52.000+0000] {task_command.py:410} INFO - Running <TaskInstance: applicants.load manual__2023-06-10T15:56:39.147730+00:00 [running]> on host 9e894d1b1662
[2023-06-10T15:56:52.099+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='applicants' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-06-10T15:56:39.147730+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-10T15:56:39.147730+00:00'
[2023-06-10T15:56:52.100+0000] {sql.py:262} INFO - Executing: 
        INSERT INTO applicants (name_and_surname, age, adress, preffered_language, cognitive_score) values(?,?,?,?,?)",
                               row['Name-surname'],row['Age'], row['Adress'], row['Preffered-language'], row['Cognitive-score'], row['Preffered-language'])
                              
[2023-06-10T15:56:52.108+0000] {base.py:73} INFO - Using connection ID 'MssqlConn' for task execution.
[2023-06-10T15:56:52.181+0000] {base.py:73} INFO - Using connection ID 'MssqlConn' for task execution.
[2023-06-10T15:56:52.216+0000] {sql.py:375} INFO - Running statement: 
        INSERT INTO applicants (name_and_surname, age, adress, preffered_language, cognitive_score) values(?,?,?,?,?)",
                               row['Name-surname'],row['Age'], row['Adress'], row['Preffered-language'], row['Cognitive-score'], row['Preffered-language'])
                              , parameters: None
[2023-06-10T15:56:52.221+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "src/pymssql/_pymssql.pyx", line 459, in pymssql._pymssql.Cursor.execute
  File "src/pymssql/_mssql.pyx", line 1087, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1118, in pymssql._mssql.MSSQLConnection.execute_query
  File "src/pymssql/_mssql.pyx", line 1251, in pymssql._mssql.MSSQLConnection.format_and_run_query
  File "src/pymssql/_mssql.pyx", line 1789, in pymssql._mssql.check_cancel_and_raise
  File "src/pymssql/_mssql.pyx", line 1835, in pymssql._mssql.raise_MSSQLDatabaseException
pymssql._mssql.MSSQLDatabaseException: (102, b"Incorrect syntax near '?'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "src/pymssql/_pymssql.pyx", line 476, in pymssql._pymssql.Cursor.execute
pymssql._pymssql.ProgrammingError: (102, b"Incorrect syntax near '?'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")
[2023-06-10T15:56:52.233+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=applicants, task_id=load, execution_date=20230610T155639, start_date=20230610T155651, end_date=20230610T155652
[2023-06-10T15:56:52.253+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 58 for task load ((102, b"Incorrect syntax near '?'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\nDB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n"); 14418)
[2023-06-10T15:56:52.278+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-10T15:56:52.310+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
