[2023-06-13T13:22:58.395+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trial_exam_ETL.create_db_tables_in_sql_server manual__2023-06-13T13:22:51.159530+00:00 [queued]>
[2023-06-13T13:22:58.407+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trial_exam_ETL.create_db_tables_in_sql_server manual__2023-06-13T13:22:51.159530+00:00 [queued]>
[2023-06-13T13:22:58.408+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-13T13:22:58.429+0000] {taskinstance.py:1327} INFO - Executing <Task(MsSqlOperator): create_db_tables_in_sql_server> on 2023-06-13 13:22:51.159530+00:00
[2023-06-13T13:22:58.436+0000] {standard_task_runner.py:57} INFO - Started process 2560 to run task
[2023-06-13T13:22:58.440+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trial_exam_ETL', 'create_db_tables_in_sql_server', 'manual__2023-06-13T13:22:51.159530+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpp313l3oh']
[2023-06-13T13:22:58.441+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask create_db_tables_in_sql_server
[2023-06-13T13:22:58.525+0000] {task_command.py:410} INFO - Running <TaskInstance: trial_exam_ETL.create_db_tables_in_sql_server manual__2023-06-13T13:22:51.159530+00:00 [running]> on host 9e894d1b1662
[2023-06-13T13:22:58.618+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trial_exam_ETL' AIRFLOW_CTX_TASK_ID='create_db_tables_in_sql_server' AIRFLOW_CTX_EXECUTION_DATE='2023-06-13T13:22:51.159530+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-13T13:22:51.159530+00:00'
[2023-06-13T13:22:58.622+0000] {sql.py:262} INFO - Executing: 
        USE trialexam;

        DROP TABLE dbo.applicants;
        DROP TABLE dbo.classes;

        CREATE TABLE dbo.classes (
            id INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
            name VARCHAR(100)
        );

        INSERT INTO dbo.classes 
        VALUES ('Panthera'), ('Celadon');

        CREATE TABLE dbo.applicants (
            id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
            name_surname VARCHAR(100),
            age INT,
            address VARCHAR(100),
            preferred_language VARCHAR(50),
            cognitive_score int,
            class_id INT

            CONSTRAINT FK_applicants_classes FOREIGN KEY (class_id)
                REFERENCES trialexam.dbo.classes (id)
        );
    
[2023-06-13T13:22:58.645+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `sqlserver` isn't defined
[2023-06-13T13:22:58.653+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=trial_exam_ETL, task_id=create_db_tables_in_sql_server, execution_date=20230613T132251, start_date=20230613T132258, end_date=20230613T132258
[2023-06-13T13:22:58.671+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 110 for task create_db_tables_in_sql_server (The conn_id `sqlserver` isn't defined; 2560)
[2023-06-13T13:22:58.692+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-13T13:22:58.744+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
